### ISSUE TITLE
Incorrect image shown in Lab 2

### ISSUE THREAD

**Issue by GregEwens** [Kevin-Sim/SET08103#1]
Lab 2 description has an incorrect image showing for one of the steps. The image immediately following "To test our new image, select Create Container with it selected and use the following properties:" is a copy of a previous image used for creating the mongo-db container. The image should show the sha name in the _Image ID or name_ field and the network bridge added in the _Run options_ as shown below

![image](https://user-images.githubusercontent.com/62880934/151533589-10941288-a2e5-49f2-9878-def5fdb97b63.png)

**Comment by Kevin-Sim** [comment]
Thanks Now Fixed
